# Generated by Django 4.0.5 on 2022-09-16 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('number', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da liberação do setor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edição')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='sectorsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sectors', verbose_name='Imagem do setor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do envio da imagem')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edição da imagem')),
            ],
        ),
        migrations.CreateModel(
            name='userSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('N', 'Negado'), ('A', 'Aceito')], default='P', max_length=1)),
                ('description', models.TextField(blank=True, default='', verbose_name='Motivo da liberação')),
                ('supervisor', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da liberação do setor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edição')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário/Setor',
                'verbose_name_plural': 'Usuários/Setores',
            },
        ),
        migrations.CreateModel(
            name='sectorsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do setor')),
                ('is_active', models.BooleanField(default=True, verbose_name='O setor ta ativo?')),
                ('desactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação do setor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do setor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edição das informações do setor')),
                ('branchName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.branch', verbose_name='filial')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.sectorsimage', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do setor')),
                ('is_active', models.BooleanField(default=True, verbose_name='O setor ta ativo?')),
                ('desactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação do setor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do setor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edição das informações do setor')),
                ('branchName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.branch', verbose_name='filial')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.sectorsimage', verbose_name='Imagem')),
                ('sectorGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.sectorsgroup', verbose_name='Grupo de setores')),
            ],
            options={
                'verbose_name': 'SubSetor',
                'verbose_name_plural': 'SubSetores',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricaluserSectors',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('N', 'Negado'), ('A', 'Aceito')], default='P', max_length=1)),
                ('description', models.TextField(blank=True, default='', verbose_name='Motivo da liberação')),
                ('supervisor', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data e hora da liberação do setor')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='última edição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Usuário/Setor',
                'verbose_name_plural': 'historical Usuários/Setores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalsectorsImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100, verbose_name='Imagem do setor')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data e hora do envio da imagem')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última edição da imagem')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sectors image',
                'verbose_name_plural': 'historical sectors images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalsectorsGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do setor')),
                ('is_active', models.BooleanField(default=True, verbose_name='O setor ta ativo?')),
                ('desactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação do setor')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de criação do setor')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última edição das informações do setor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branchName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectors.branch', verbose_name='filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectors.sectorsimage', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'historical Setor',
                'verbose_name_plural': 'historical Setores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalsectors',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do setor')),
                ('is_active', models.BooleanField(default=True, verbose_name='O setor ta ativo?')),
                ('desactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação do setor')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de criação do setor')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última edição das informações do setor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branchName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectors.branch', verbose_name='filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectors.sectorsimage', verbose_name='Imagem')),
                ('sectorGroup', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectors.sectorsgroup', verbose_name='Grupo de setores')),
            ],
            options={
                'verbose_name': 'historical SubSetor',
                'verbose_name_plural': 'historical SubSetores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalbranch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('number', models.IntegerField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data e hora da liberação do setor')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='última edição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Filial',
                'verbose_name_plural': 'historical Filiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
